---
vagrant_version: 2.1.1
vagrant_download_url: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.rpm
vagrant_pkg: vagrant_{{ vagrant_version }}.x86_64.rpm
